stages:
  - test
  - deploy

image: node:18

cache:
  paths: -node_modules/

before_script: -npm install

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r public/ ./public
  artifacts:
    paths:
      - public
  only:
    - main
